export default {
    back: 'رجوع',
   name: 'عنوان' ,
   note: 'ملاحظه',
   price: 'السعر',
   add: 'اضافة',
   expencese: 'التكاليف',
   today_expenses: 'تكالييف اليوم',
   expencese_counter:'التكاليف',
   less_then:'مصروف اليوم',
   today_items_list:'قائمة تكاليف اليوم',
   no_items:'لا يوجد اي عنصر اليوم',
   you_can_add:'بمكانك اضافة عنصر جديد عن طريق علامة الزائد',
   week_expencises:'تكاليف الاسبوع',
   warning:"تحذير!",
   message:"هل تريد حذف العنصر ؟",
   cancelText:"لأ , اريد الالغاء",
   confirmText:"نعم , اريد",
   important:'مهم',
   message_add_budget:'الرجاء اضافة ميزانتك اليوميه',
   ex:"مثال.50",
   submit:"اضافة",
   cancel:"الغاء",
   avg:"متوسط صرفك",
   tut_welcome:"مرحبا بك  في تطبيق تكاليف",
   tut_welcome_sub:"في هذا التطبيق نساعدك في تتبع مصاريفك لتوفير اكبر قدر من المال",
   tut_how_to_add_items:"طريقة الاضافة",
   tut_how_to_add_items_sub:'طريقة الاضافة جدا بسيطه فقط عليك النقر على اشاره الزائد ثم تختار نوع الصرف مثلا ايقونت البيتزا تدل على الاكل ',
   tut_change_exp:'طريقة تغير حد مصروفك اليومي',
   tut_change_exp_sub:'لقد اضفنا حد المصروف اليومي لمساعدك في توفير اكبر قدر من المال ب امكانك تغير الحد عن طريق النقر على ايقونت العدادات',
   next:"التالي",
   skip:'اختصر',
   cancel_expeneces:"الغاء",
   submit_expeneces:'حفظ',
   err_msg:'الرجاء اضافة العنوان و السعر لاضافة العنصر',
   transportation:"مواصلات",
   entertainment:"الترفيه",
   food:"اكل",
   where_expencise_go:"احصائيات",
   no_data_yet:"لا يوجد معلومات كافيه",
   d_home:'الرئيسيه',
   d_history:'سجل تكاليفك',
   no_history:'لا يوجد معلومات',
   mas_history_title:'سجل',
   mas_history:'في هذه الشاشة يمكنك رؤية جميع تكاليفك السابقة يتم تحديث السجل بشكل يومي',
   about_us:"من نحن",
   created: 'تم انشاء هذا التطبيق من قبل فريق اصرار' ,
   fallow:"لمزيد من التطبيقات تابعنا على فيسبوك" ,

   


}