export default {

    back: 'Back',
    name: 'Name' ,
    note: 'Note',
    price: 'Price',
    add: 'Add',
    expencese: 'Expencese',
    today_expenses: 'Today Expencise',
    expencese_counter:'Expencese',
    less_then:'Less then',
    today_items_list:'Today Items List',
    no_items:'You Have No items Today',
    you_can_add:'You Can Add Throw the Plus Sign',
    week_expencises:'Week Expencises',
    warning:"Warning!",
    message:"are you sure you want to delete this item ?",
    cancelText:"No, cancel",
    confirmText:"Yes, delete it",
    important:'Important!',
    message_add_budget:'Please Add Your Daly Budget',
    ex:"ex.50",
    submit:"SUBMIT",
    cancel:"CANCEL",
    avg:"avg daily exp",
    tut_welcome:"Welcome To Expenece Tracker!",
    tut_welcome_sub:"In this app we will help you to track your daly expeneces",
    tut_how_to_add_items:"How To Add item\'s",
    tut_how_to_add_items_sub:'it\'s very simpel just press on the plus buttons \n you will find many icons every icon represent something \n ex.bus icon repeset transportation etc',
    tut_change_exp:'How To Change Your Daly Expeneces Limit',
    tut_change_exp_sub:'we have added the daly expeneces limit help you save some money you can change the limit any time you want throw the presing the gear icon in the to right the screen',
    next:"Next",
    skip:'Skip',
    cancel_expeneces:"cancel",
    submit_expeneces:'save',
    err_msg:'Please At least add the title',
    transportation:"Transportation",
    entertainment:"Entertainment",
    food:"Food",
    where_expencise_go:"Analytics",
    no_data_yet:"No Enough Data Yet",
    d_home:'Home',
    d_history:'History',
    no_history:'There is No History Yet',
    mas_history_title:'History',
    mas_history:'in this screen you can see all your expenses it was added to the app ( the will update daly )',
    about_us:"About Us",
    created:'This App Created by Israra Team',
    fallow:'You Can Fallow Us On Facebook To See Our Lates Apps',
 
    
    


 
}